from ops_client.project.designate.zones import ZoneManager
from ops_client.project.designate.recordsets import RecordSetManager
from ops_client.project.designate.tlds import TldManager
from ops_client.project.designate.blacklists import BlackListManager
from ops_client.project.designate.quotas import QuotaManager
from ops_client.project.designate.pools import PoolManager
from ops_client.project.designate.nameservers import NameServerManager
from ops_client.project.designate.limits import LimitManager
from ops_client.project.designate.floatingips import FloatingIPManager
from ops_client.project.designate.tenants import TenantManager
from ops_client.project.designate.count import CountManager
